// ...existing code...

export const features = {
    // ...existing code...
    enableGpt51CodexMaxPreview: true, // Enable GPT-5.1-Codex-Max (Preview) for all clients
    // ...existing code...
};

// ...existing code...